### ISSUE TITLE
Direct install not showing

### ISSUE THREAD

**Issue by TESTACC2133** [ZeroOneZero/Root-Bluestacks-with-Kitsune-Mask#1]
the only option that shows to me is select and path a file, i try unlock with bstweaker, and grant acess through bluestacks config, but no use,

**Comment by ZeroOneZero** [comment]
> the only option that shows to me is select and path a file, i try unlock with bstweaker, and grant acess through bluestacks config, but no use,

See if this guide, combined with mine, will help. I'm investigating your issue independently. Realistically, without reinstalling Windows for a clean start, troubleshooting will be challenging due to numerous potential factors. Nonetheless, I'll try.
[Link](https://platinmods.com/threads/how-to-install-kitsune-mask-magisk-delta-on-android-emulators-easy-installation.165579/)
